jobs:
  refresh-commit-deploy:
    runs-on: ubuntu-22.04

    env:
      RENV_PATHS_ROOT: ~/.local/share/renv
      API_USER_TOKEN: ${{ secrets.API_USER_TOKEN }}
      GITHUB_PAT: ${{ secrets.GH_PAT }}
      SHINYAPPS_ACCOUNT: ${{ secrets.SHINYAPPS_ACCOUNT }}
      SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
      SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.2'

      - name: System dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake libnode-dev libx11-dev pandoc \
            libgdal-dev gdal-bin libgeos-dev libproj-dev proj-data proj-bin \
            libudunits2-dev libcurl4-openssl-dev libssl-dev libxml2-dev libpng-dev \
            pkg-config libfontconfig1-dev libfreetype6-dev libharfbuzz-dev libfribidi-dev

      - uses: r-lib/actions/setup-renv@v2
        env:
          GITHUB_PAT: ${{ secrets.GH_PAT }}

      - name: Update GA data cache
        run: |
          date
          time Rscript scripts/update_ga_data.R
          date
